### ISSUE TITLE
🚀 Improvement: Make SQL statements work

### ISSUE THREAD

**Issue by MayNiklas** [the-rising-tide/certificate-bot#3]
We maybe have a _tiny_ problem in our code: it could be possible, that all of our SQL conjunction statements don't work completely as expected.

The "and" statements are not implemented correctly. The statements effectively translate to:
`select(dbm.Domains).where(dbm.Domains.domain == domain_input['domain'])` while the rest of the statement is getting ignored.

In consequence, it's not possible, that two users watch the same domain.
Also a person is able to delete another persons domain from the watch list.

**Comment by nonchris** [comment]
Hello Sir,
we take your feature request very serious.
We'll add it to our roadmap!

Kind regards
The rising tide

**Comment by nonchris** [comment]
Got fixed in #4 
Closing issue.
